<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IsAotCompatible>true</IsAotCompatible>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <Version>1.0.0-preview.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Include="build\**" Pack="true" PackagePath="buildTransitive\" />
    <Compile Remove="Community\**" />
    <TfmSpecificPackageFile Include="Community\**">
      <PackagePath>lib\$(TargetFramework)\Community\%(RecursiveDir)%(Filename)%(Extension)</PackagePath>
      <PackageCopyToOutput>true</PackageCopyToOutput>
    </TfmSpecificPackageFile>
    <Compile Remove="ReactiveUI\**" />
    <TfmSpecificPackageFile Include="ReactiveUI\**">
      <PackagePath>lib\$(TargetFramework)\ReactiveUI\%(RecursiveDir)%(Filename)%(Extension)</PackagePath>
      <PackageCopyToOutput>true</PackageCopyToOutput>
    </TfmSpecificPackageFile>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>
</Project>